### ISSUE TITLE
How to organize Fields correctly so they show the same way on a PDF

### ISSUE THREAD

**Issue by CoryShubert** [giowck/symphytum#106]
New to Symphytum and didn't see this on the Wiki, so asking here.  Hope it is correct.
I have created a form for beer recipes and the Form view and Table view are like this:
![Screen Shot 2019-11-04 at 8 48 06 AM](https://user-images.githubusercontent.com/57360259/68129827-dc60bc00-fedf-11e9-933e-dc49aaee4c67.png)
![Screen Shot 2019-11-04 at 8 48 15 AM](https://user-images.githubusercontent.com/57360259/68129836-dff44300-fedf-11e9-99e0-a997bed671a9.png)
But when I save as a PDF, the fields for Steps and Notes are AFTER the image field for the finished beer:
<img width="1108" alt="Screen Shot 2019-11-04 at 8 49 48 AM" src="https://user-images.githubusercontent.com/57360259/68129932-15992c00-fee0-11e9-9af2-8114c99a0c55.png">
Why is this happening and can I make it so the image is the LAST field?

**Comment by joshirio** [comment]
Unfortunately the printing functionality is very basic. There are no configuration options for it, so the default order of the fields in the PDF is the same as the order in which the fields got created (added to the collection).

**Comment by CoryShubert** [comment]
Ok, so if I were to delete a field and add it later on, would it align in the correct order then?  Also, is there a tutorial for using the whole copy and paste and reusing collections?  Thank you.

**Comment by joshirio** [comment]
> if I were to delete a field and add it later on, would it align in the correct order then?

If you delete a field and add it back it will be printed on the last position.

> Also, is there a tutorial for using the whole copy and paste and reusing collections?

Not sure what you mean by _whole copy_ but it's not possible to copy data between collections, the only workaround is to export it to CSV first and open it with you favorite spreadsheet app, and copy & paste manually.
