### ISSUE TITLE
Auto width all columns

### ISSUE THREAD

**Issue by silviulaurentiu** [giowck/symphytum#116]
It will be helpful if there will be the option to automatically adjust the width of all columns into a click. Or to select all columns, then to have auto width option or to double click between two columns to auto width all of them.

**Comment by joshirio** [comment]
I'm thinking about adding an action in the menu to set the table column width to fit the content. Something like "View->Table View->adjust column width to content".

The only way to manually activate auto width for each column is to double click on the space between the columns in the table header

![rvvo2qnaMK](https://user-images.githubusercontent.com/12795018/73595642-46a6ee00-451b-11ea-9289-669685a4903f.gif)

**Comment by joshirio** [comment]
Ended up implementing this as an additional setting (Column width: adjustable/automatic)

![4jZ0LnRWAj](https://user-images.githubusercontent.com/12795018/73596415-43633080-4522-11ea-9c17-631b3703d335.png)
