### ISSUE TITLE
Keep the column width of tables when the user switch from one table to other

### ISSUE THREAD

**Issue by silviulaurentiu** [giowck/symphytum#119]
When the user select another collection than the current selected one, the table column widths are  reset to default width (a small one) and each time have to be readjusted to the be able to see the long content of records.
It will be helpful to keep the set width of each table (collection) or to have the option all columns to be automatically adjusted to the best width in order to fit and to see the content.

**Comment by joshirio** [comment]
If I didn't miss anything this should be already working
![ybEZApwRiJ](https://user-images.githubusercontent.com/12795018/73557386-640f8580-4451-11ea-8ab3-a9633cd5c234.gif)

If not, please comment and I'll reopen the issue

**Comment by silviulaurentiu** [comment]
I tried an for me is not working
![Yk9FwvfFMM](https://user-images.githubusercontent.com/14875058/73573623-794dd980-447c-11ea-8b07-756f13edef3f.gif)

**Comment by silviulaurentiu** [comment]
![image](https://user-images.githubusercontent.com/14875058/73573664-9a162f00-447c-11ea-8a6e-56e72ea35d05.png)

**Comment by joshirio** [comment]
OK I was able to reproduce it. This bug happens only if the columns in the table view have been reordered (by drag & drop).
