### ISSUE TITLE
No data to export when using a duplicate collection with data structure only

### ISSUE THREAD

**Issue by TMCautomates** [giowck/symphytum#121]
I have created a 'collection' that I would like to use as a template for creating survey data, however, when I duplicate the collection and create new records within the collection and try to export the data, it shows 0 items selected and exporting all data only gives me headings. This could be when I have entered 100 lines of data in the table view. I have tried this on the Windows portable and EXE versions and they both give the same result on two different Windows machines and I have the same issue on a laptop running Ubuntu. I have created a template with 500 records, and duplicated this collection and I am able to export those 500 lines of data, but if I duplicate a record, the duplicate will not be added to the export.

**Comment by joshirio** [comment]
Yes that's a bug, I was able to reproduce it. This affects also printing. Looks like during export/print data from the records can't be accessed.

Thanks for the report.

**Comment by joshirio** [comment]
Looks like the `_id` column inside the SQLite database remains NULL in some cases when a collection is duplicated, but it should contain an automatically incrementing number when a new record is added.
