### ISSUE TITLE
Sync fails - adding and than removing the file before sync

### ISSUE THREAD

**Issue by darksidestarea** [giowck/symphytum#128]
Hi, while adding one file to record and removing it immediately, next file sync (to generic folder) is failing with message that is not possible to erase that file (since it never existed on sync location).

/Alex

**Comment by joshirio** [comment]
Yes that is right, thanks for reporting.

Temporary workaround to recover from such broken sync cycle:
is to create a file with the same file name as shown in the error message and to place it inside the cloud service's directory along with all other files, so that deleting succeeds...

**Comment by darksidestarea** [comment]
Nah - too lazy to write filename :-) (not possilbe to copy text from error window (another feature suggestion)) - instead, i am deleting whole remote directory and syncing again..

/Alex

**Comment by joshirio** [comment]
fixed by https://github.com/giowck/symphytum/commit/2cf0f5cd4b1274b52e5185a4f365359324cc7f87
