### ISSUE TITLE
No forum, no help email, no way to ask questions.

### ISSUE THREAD

**Issue by Innomen** [giowck/symphytum#13]
That's a huge issue.

I've got a bunch of questions and suggestions. What do I do with them?

**Comment by Innomen** [comment]
I can't even find where this app hides the database it's modifying. The usual suspect locations are dry of leads.

The obvious locations should be either a clearly marked folder in the install folder, or Libraries\Documents, or users application data.

**Comment by jniggemann** [comment]
Mine is located at `/home/<user>/.local/share/data/giowisys/Symphytum/data.db`

**Comment by Innomen** [comment]
I must have a different operating system, but thank you, that will no doubt inform future searches :)
