### ISSUE TITLE
Where is the database actually stored (win7)? Why can't I export the whole thing?

### ISSUE THREAD

**Issue by Innomen** [giowck/symphytum#14]
I'm experimenting with cloud sync but I want to back everything up first.

**Comment by johnnyzero** [comment]
C:\Users\[username]\AppData\Local\giowisys

**Comment by Innomen** [comment]
Hehe, better late than never. Thanks :)

**Comment by Etnolog** [comment]
Hi Innomen, I'm trying for some time to establish cloud sync, without success. If you managed to do that, would you please share the way? :)

**Comment by Innomen** [comment]
I meant manually. I eventually put using this tool on hold at all. Tiddlywiki ended up meeting my needs better. Fwiw/ymmv

**Comment by Etnolog** [comment]
Ok, thanks. Perhaps I'm doing something wrong with cloud synchronizing. I'll try also to do it manually, as suggested by johnnyzero.

**Comment by Innomen** [comment]
Are you syncing across the net or do you just want to sync across local devices?

If it's local you might look into this: https://www.getsync.com/

**Comment by Etnolog** [comment]
Well, I'd just like to have a cloud backup of data I put in Symphytum on my office computer and be able to access the same data when I open the application and sync with my home laptop. So, it's syncing across the net.

**Comment by joshirio** [comment]
by implementing issue #38 it would be possible to use a custom sync solution or service other than dropbox, maybe that would be useful.
