### ISSUE TITLE
version update

### ISSUE THREAD

**Issue by Taskitaly** [giowck/symphytum#15]
Hello,
I'm currently using the 1.1 version downloaded from Giowysis, should I download the updated version ?
Will all my existing data automatically be saved in the new version ?

**Comment by Taskitaly** [comment]
...sorry I forgot to mention that I'm using Symphytum on both Windows 7 pro and Ubuntu

**Comment by AlexJiang777** [comment]
After Updated to v.2.0 only one change detected - it's by launch error "The ordinal not found: The ordinal 3873 could not be located in the dynamic link library LIBEAY32.dll. OK?" Pls comment, was it really necessary to update just to gain this warning???
Sincerely,
Alex
(On Win7 x64)
![sympthum_warn](https://cloud.githubusercontent.com/assets/20130267/16571835/de6f139e-4294-11e6-88de-74f7a110c0e4.jpg)
