### ISSUE TITLE
Display problems in Linux on HiDPI displays at 2x scale

### ISSUE THREAD

**Issue by themacg33k** [giowck/symphytum#18]
As in the screenshot below, there's issues running Symphytum on Linux using a HiDPI display at 2x scaling. Among them:
- Field elements do not respect scale; text contained within does.
- Sidebar text does not respect scale.
- Columns in the form view do not respect scale.

System is Ubuntu 15.04 with the display scale set to 2.0 to accommodate the HiDPI (13-inch 3200 x 1800px) display.

![Screenshot from 2015-05-02 11 53 57](https://cloud.githubusercontent.com/assets/520865/7442344/72f718ac-f0c2-11e4-8e48-2cdca176b494.png)

**Comment by chris-morgan** [comment]
Very similar results on Windows with Symphytum 2.0 on Windows 10 at 200% scaling. This is what it looks like on first run:

<img src="https://cloud.githubusercontent.com/assets/392868/17082187/0647e238-51b8-11e6-8c3a-06ac91c8b2bb.png" width="491" height="280" alt="Screenshot of Symphytum 2.0 running for the first time on Windows 10 at 200% scaling: completely unusable">

In this form it’s *completely* unusable.

If you can provide a probable patch, I can try to build it—or if you can produce a build, I can test it.

**Comment by stax76** [comment]
At 288% DPI what I use it's even worse, too bad because the app looks very promising.

**Comment by giowck** [comment]
Unfortunately I don't have access to a HiDPI monitor to investigate this issue.
On macOS it works fine though, so it affects only linux and windows I think.

**Comment by giowck** [comment]
As a workaround for windows users until next version is out:

click with the right mouse button on the symphytum link (desktop or menu) and navigate to the compatibility tab, then select "Override high DPI scaling behavior" and choose "System".

Here an example: https://archive.is/831tL or https://archive.is/lrtOs#selection-253.70-253.105

This scales the application to a virtual fixed resolution surface, making it at least readable and usable. Of course, text is slightly blurry but acceptable.

A fix for windows and linux (tested with 1x font scaling factor) will be committed soon...
