### ISSUE TITLE
symphytum 2.0 installation loses QT5 library when installing windows version in windows 10 pro on bootcamp partition

### ISSUE THREAD

**Issue by HKSA** [giowck/symphytum#20]

**Comment by HKSA** [comment]
Program doesn't start - error to effect that: "program has lost QT platform..."

**Comment by giowck** [comment]
Sorry I have not a windows 10 system to test this. Windows 7 and 8 works as expected.
Can you be more precise what exact error message is shown?

**Comment by giowck** [comment]
OK I got the exact error, working on it. Will release a new windows installer once fixed.

**Comment by giowck** [comment]
Please download the installer again, should work fine now.
Thanks for reporting.

**Comment by HKSA** [comment]
Hi Giorgio,

 

Thanks/Danke! It works perfectly now!

 

Kind regards from Down Under,

 

Horst

**Comment by Etnolog** [comment]
Could you, please, post a link to symphytum 2.0 download? Through Google I can find only 1.1

Thanks.

**Comment by giowck** [comment]
Hi Etnolog, visit the main site: https://giowck.github.io/symphytum/
and click on the download button for your platform.
In case of windows, yes only the setup .exe file is required.

**Comment by Etnolog** [comment]
Hi giowck, thank you for the instruction! I downloaded and installed 2.0, but I can't see any difference between the new and the old version regarding earlier mentioned improvements regarding inserting links and e-mail addresses.

Anyway, by main concern is regarding letters that are supported in symphytum i.e. in Croatian language there are letters such as č, ć, š, đ, ž, which can be typed into fields, but when exporting the base they get lost and turn into different kind of signs, but not the original letters. Is there a way to enable support for other European alphabets besides only the English one?
