### ISSUE TITLE
Import/Export CSV: quotation marks not allowed

### ISSUE THREAD

**Issue by buhtz** [giowck/symphytum#29]
The CSV Import and Export doesn't allow fields with __quotation marks__.

e.g.
`"john";"doe"`

It would be nice to have this. And it would be much nicer if the character `"` could be userdefined. Sometimes e.g. `|` is needed.

**Comment by andrewbarbour** [comment]
This would be a very nice feature - however I think there are a few more where there is no easy desktop workaround.  Has anyone considered putting bounties on bugs/features?

**Comment by joshirio** [comment]
Field names with double quotes are now possible, also in export/import, so closing this.

about:

> It would be nice to have this. And it would be much nicer if the character " could be userdefined. Sometimes e.g. | is needed.

It appears that every other character works now in import/export and field names.
I'm not sure about what you mean. Custom CSV separator character?
Please comment or open a new issue if this persists in the new release or if I missed something.
