### ISSUE TITLE
Modify field dropdown field types greyed out.

### ISSUE THREAD

**Issue by digedits** [giowck/symphytum#30]
Unable to change field type from text to link, etc.
<img width="287" alt="capture" src="https://user-images.githubusercontent.com/31009156/29275829-76d250cc-80da-11e7-9018-7f962c60a5f0.PNG">

**Comment by giowck** [comment]
Changing a field type is not allowed after creation because data types may not be compatible. Data migration from one field type to another is not planned at this point.
