### ISSUE TITLE
Non-admin installation on Windows

### ISSUE THREAD

**Issue by jlehtoma** [giowck/symphytum#51]
The current installer requires admin privileges, which regular user often doesn't have in enterprise/organizational environment. Would it be possible to generate a non-installer-based build/distribution on Windows? I.e. a installerless zip or similar.

**Comment by joshirio** [comment]
Implemented in #52 as fully portable mode, meaning settings and all data is saved to the local "portable_data" directory.

Next release, v2.3, will provide this portable distribution method.

Thanks for the suggestion.

**Comment by jlehtoma** [comment]
Sweet, thanks!
