### ISSUE TITLE
File list - show path for added file

### ISSUE THREAD

**Issue by tompad2** [giowck/symphytum#57]
Hi!

Is it possible to add option to show path of added file in FileList?

Like:
Nameoffile.rpp   C://Document/EDM/Nameoffile.rpp

Thanks for creating this application - I like!

Regards
Thomas

**Comment by joshirio** [comment]
I'm thinking about your suggestion but see little use to it, because once a file is added to the file list it is imported to the database as a copy of the original file. In this way the original location of the file is no longer relevant.

Or is it still useful to see where the original file was imported from, as documentary value?
Are there any use cases for this?

**Comment by tompad2** [comment]
Yes, I am using it like a database over project done with my DAW Reaper (music app) and see where the
projects is located would help a whole lot (with clickable links opening fileexplorer would be super!)

**Comment by joshirio** [comment]
It is doable but there are some limitations. Currently, if a file is added to the file list, the file is copied and saved inside the database (files directory) and not linked like a shortcut, so even if you double click the file it will open the file inside the folder of the database and not your original imported file. I could add the feature of remembering where a file was copied from (original import path) but this will not change the current behavior of opening the imported file on double click.

So if this is implemented it will be useful only as historical reference to know where a file was imported from.

**Comment by tompad2** [comment]
Remembering original import path would be very nice for my purpose!
How about making it selectable when doubleclick the file (Dialog Box) - open original import path with file explorer OR open the file inside database folder?

**Comment by joshirio** [comment]
I think I could add a context menu entry (right mouse click) which says "open original file path" or something similar while keeping the current expected double click behavior.

Thanks for the suggestion.

**Comment by tompad2** [comment]
Great - looking forward to 2.4! Thanks!
