### ISSUE TITLE
export pictures and files

### ISSUE THREAD

**Issue by damaxel** [giowck/symphytum#81]
Hi there!
Thanks for the great tool. I think about using it for a collection of 10.000+ items.
I was wondering, if its possible to export all the pictures and files saved in the database. As far as I understand, the export function gives only a csv file that includes the initial file name. But how to get the file to save or backup it.

Thanks for the help!
Best,
Maximilian

**Comment by joshirio** [comment]
Hi, you can backup your database by using the backup dialog from Menu->File->Backup

This will create a Symphytum Backup file *:syb which contains all your data. This file can be imported by using the same dialog to another Symphytum installation.

If you just want to manually access and copy the files all at once you can go to the files directory and just copy all files.

Please see the FAQ entry: [where does Symphytum store my data?](https://github.com/giowck/symphytum/wiki/Frequentry-Asked-Questions-(FAQ)#where-does-symphytum-save-my-files-and-databases)

Note that the CSV export format is not intended for binary files this is why files are excluded. The CSV export format is a convenient text based file format for spreadsheets programs.

**Comment by damaxel** [comment]
Thanks for your help!
