### ISSUE TITLE
editing forms (and database structure) in "lock form layout" mode?

### ISSUE THREAD

**Issue by damaxel** [giowck/symphytum#82]
The "lock form layout" mode is intended to prevent unwanted field movements when working with database content. That is a very good improvement. Thanks for that!
I would like to suggest a general differentiation between the essential work on the database structure (including the form/field design) and the work with the database content. Why not providing two different modes? A simple mode, for ordinary and daily content editing (create and edit content) without the chance to cause larger damage. And one advanced mode (to be activated via menu -> activation by accident must be avoided) for activities compared to hearth surgery, like deleting and adding fields, deleting all the content, deleting collections, etcetera.
In my case, I would like to set up a database for my father’s collection of model railroads. Later, he will be the one to work with the content only. If it’s too easy to produce major changes by accident, I am quite certain, the database will last just a few days. For sure, sooner or later, he would push all the icons in the top menu and/or the left click menu...

What do you think about this suggestion?

**Comment by joshirio** [comment]
I think implementing another view just for input is a bit too far, but I also see the point you make for the use case where  users that are not that "comfortable with computers" might cause unwanted damage.

So maybe a "safe content edit mode" can be added to the edit menu Edit->Enable safe editing or "simple content edit mode" where all destructive actions are disabled (greyed out) but also actions like field addition, collection creation and so on. This mode would also automatically enable the lock form layout action. The only permitted actions would be record addition, editing and deletion.

**Comment by damaxel** [comment]
That sounds great! 
Thanks a lot!
