### ISSUE TITLE
CSV Export - file name of picture?

### ISSUE THREAD

**Issue by damaxel** [giowck/symphytum#83]
I tested the export functionalities and faced some issue regarding file names of embedded pictures. 
The CSV file contains the initial file name of the picture. Is this useful? I guess, it would be better to use the new file name given to the picture by Smphytum when saving it to the "\giowisys\Symphytum\files" directory. As a result, it would be much easier to connect the information from the database with the related pictures to use it in other applications.

What dou you think?

**Comment by joshirio** [comment]
The current file name as used by Symphytum's internal file storage is now also appended to the CSV output

![EXCEL_eqvZBC318M](https://user-images.githubusercontent.com/12795018/67245677-d937eb80-f45c-11e9-9d09-b200a1fd39f6.png)
