### ISSUE TITLE
Translation lang file

### ISSUE THREAD

**Issue by ppasserini** [giowck/symphytum#93]
Hi,
first of all thank you for your great software.
I'm trying the portable version of version 2.5 an I'm wondering where I should copy the qt_lang.qm file in order to use it.

Thanks

**Comment by joshirio** [comment]
Symphytum loads the qm files from the bundled resource (.qrc) file, so it's not possible to load custom files without compiling from sources.

What language are you looking for? Symphytum is currently only available in french, german, polish and english.

**Comment by ppasserini** [comment]
....and Italian, I saw the file. If I'm wrong I'll take care of translate from Eng to Ita or just update it.
It's a pity to not be able to load custom language file. Is it related to QTLib? Could be possible to point a XML/TXT config file to set a variable and point a custom file?

Thanks

**Comment by joshirio** [comment]
The italian file is just a placeholder for this issue: https://github.com/giowck/symphytum/issues/6

It's actually empty and would require someone to translate it first then, once included into Symphytum, it would display all strings in italian on systems that have the locale set to it_IT.

> Could be possible to point a XML/TXT config file to set a variable and point a custom file?

No, Qt uses it's own file format for translations.For more info on how to translate Symphytum, see the following [doc](https://github.com/giowck/symphytum/tree/master/doc/translation).

Would be great if anyone wants to contribute the Italian locale.

**Comment by ppasserini** [comment]
Ok, I'll do my best to take care if translation.
By the way ... it's still not clear to me, using the portable windows version, how to "select" the language right now (eng, fra, ger , pol)
Thanks

**Comment by joshirio** [comment]
> it's still not clear to me, using the portable windows version, how to "select" the language right now (eng, fra, ger , pol)

There's no setting for that, the app picks up the default system locale setting and tries to load the corresponding translation from the resources, if present.

If you think there needs to be an additional entry to select the language in the settings dialog, please feel free to open a new issue for it. Up until now, the default behavior was fine, but maybe there are use cases where this could be useful.

**Comment by ppasserini** [comment]
OK, thanks.
Step by step.....I'll translate in Italian and then I'll do some test about the "default locale" with the portable version.

**Comment by joshirio** [comment]
Great, thanks, if you need any additional help feel free to ask here or via email.

**Comment by ppasserini** [comment]
NO! Thank you for your great software! :-)

**Comment by joshirio** [comment]
Here's a test build (windows portable) with included Italian translation for the interested: https://mega.nz/#!o8YUxIgA!EoO6mAeTo-Wd6ItRJ-pnFDVu4QP84PqFVfoZeGyunHA

**Comment by ppasserini** [comment]
Tested, looks good. I'll do some test and inform you about results. Thanks!

**Comment by Bobethomas** [comment]
Yes, having a language selection would be great.  I live and work in Germany, but my native language is English.  So when I installed Symphytum, it chose German from my system settings (which are actually dual language, but since my keyboard is German the main setting is German)... but I am much more comfortable working in English...
Is there a way to install Symphytum with a switch of some sort of indicator that it should install in English?
Thanks.
